### ISSUE TITLE
Longitude and Latitude arrays in netcdf

### ISSUE THREAD

**Issue by plvoit** [cchwala/radolan_to_netcdf#11]
Hello,
thanks for your very helpful package. I converted the data from the DWD to a netcdf with your package but I'm struggling to add a projection to the resulting netcdf for further work in GIS. If I understood correctly, longitude and latitude are already added to the netcdf, so the projection would be WGS84? Why are longitude and latitude 2D arrays instead of 1D arrays? The resulting netcdf looks as follows (opened with xarray):

Coordinates:
  * x           (x) float64 -443.5 -442.5 -441.5 -440.5 ... 453.5 454.5 455.5
  * y           (y) float64 -4.759e+03 -4.758e+03 ... -3.661e+03 -3.66e+03
    latitudes   (y, x) float64 46.19 46.19 46.19 46.2 ... 55.53 55.53 55.53
    longitudes  (y, x) float64 4.676 4.688 4.7 4.712 ... 17.05 17.06 17.08 17.1
  * time        (time) datetime64[ns] 2021-07-13T00:50:00 ... 2021-07-15T23:5...
  
I would like to swap x and y to latitudes and longitudes but it does not work because they are two dimensional. Maybe I haven't really understood the RADOLAN projection yet? How can I georeference the resulting netcdf?
Sorry if this is not really a bug report but more a understanding issue.
Thanks for your help,
Paul

**Comment by cchwala** [comment]
Hi Paul. Thanks for your questions and good to hear that this packages is helpful. Projected coordinates and lon-lat can indeed be confusing. I am not an expert on this, but I'll try to explain.

> Why are longitude and latitude 2D arrays instead of 1D arrays?

The RADOLAN projection is designed so that one get's an equidistant grid with 1km spacing for Germany. Because this 2D grid is equidistant, `x` and `y`, which define the grid, can be 1D vectors.

For the lon and lat, grid things are different, though. Because of the distortion of the projection, there is no constant lon or lat value that corresponds to a constant x or y value (vertical or horizontal section of the x-y grid). Hence, lon and lat have to be provided as 2D arrays.

>  If I understood correctly, longitude and latitude are already added to the netcdf, so the projection would be WGS84? 

As far as I understand the naming conventions for coordinate systems and map projections, lon and lat coordinates are not considered projected. WGS84 rather refers to the [World Geodetic System](https://en.wikipedia.org/wiki/World_Geodetic_System), a standard coordinate system used in carography.

> I'm struggling to add a projection to the resulting netcdf for further work in GIS

I am not a GIS user, but I did a test with panoply, a NetCDF viewer, and it can correctly interpret the coordinates contained in the NetCDFs. Not sure if it uses the lon-lat coordinates or if if uses the additional info on the map projections contained as attributes in the NetCDF. If your GIS does not correctly work with the provided NetCDFs, you might be able to separately specify the projection in your GIS software. DWD provides the info [here](https://maps.dwd.de/geoserver/web/wicket/bookmarkable/org.geoserver.web.demo.SRSDescriptionPage?2&code=EPSG:1000001).

There is a lot more info on the RADOLAN grid in the docs of the fabulous Python package [`wradlib`](https://docs.wradlib.org/en/stable/notebooks/radolan/radolan_grid.html), which is also used in this package to create the x, y, lon and lat coordinates.

**Comment by plvoit** [comment]
Hi,
thanks for your swift reply and the explanation. I also tried Panoply now, its a nice tool which I didn't know yet, and it shows the projections. Thanks again for your useful package!
BTW: Maybe a grid size 1100x900 for the reprocessed data could be implemented in the radolan_product_netcdf_config.py. I changed it when I processed my files.
Paul

**Comment by cchwala** [comment]
> BTW: Maybe a grid size 1100x900 for the reprocessed data could be implemented in the radolan_product_netcdf_config.py. I changed it when I processed my files.

For the YW product (meant for RADKLIM YW, which is the 5-minute reprocessed radar climatiology) the correct grid is specified [here](https://github.com/cchwala/radolan_to_netcdf/blob/bec6b82f3797ec4d79c2cc3fa9fae810ebfa9e61/radolan_to_netcdf/radolan_product_netcdf_config.py#L120).

**Comment by plvoit** [comment]
yes, but there is also a RW-product (1 hour, reprocessed) that has the grid 1100x900
(https://opendata.dwd.de/climate_environment/CDC/grids_germany/hourly/radolan/reproc/2017_002/bin/2021/)

**Comment by cchwala** [comment]
Okay. I was not aware of that since I only use RADKLIM-YW. I opened a new issue to track the need for the extension of the config file, see #12
